<div class="container" style="margin-top: 20px">
  <div class="row">
    <div class="col-md-5 col-lg-12">
      <div class="main-card mb-3 card">
        <div class="card-body">
          <div class="position-relative form-group">
            <section>
              <label><h1>Edición de usuarios</h1></label>
            </section>
              <h2><span class="position-relative form-group-addon"><strong>Usuario: </strong><v style="color:#5bc0de; font-weight: 600;"><?=$user?></v></span></h2>
            </section>
            <div class="card-body">
              <div class="form-row">
                <div class="col-md-6">
                  <div class="position-relative form-group">
                    <label class="form-group-addon">Nombre</label>
                    <input type="text" class="form-control" aria-describedby="nombre" name="nombre" id="nombre" value="<?=$nombre?>"/>
                  </div>
                </div>
                <div class="col-md-6">
                  <div class="position-relative form-group">
                    <label class="form-group-addon">Apellido</label>
                    <input type="text" class="form-control" aria-describedby="apellido"  name="apellido" id="apellido" value="<?=$apellido?>" />
                  </div>
                </div>
              </div>
              <div class="form-row">
                <div class="col-md-6">
                  <div class="position-relative form-group">
                    <label class="form-group-addon">Rol activo</label>
                    <select class='selectpicker show-menu-arrow show-tick form-control' name="rol" id="rol">
                         <option value='2' <?=$e?>>Operador</option>
                         <option value='3' <?=$f?>>Supervisor / Analista</option>
                         <option value='4' <?=$g?>>Externo</option>
                    </select>
                  </div>
                </div>
                <div class="col-md-6">
                  <div class="position-relative form-group">
                    <label class="form-group-addon">Status</label>
                    <select class='selectpicker show-menu-arrow show-tick form-control' name="status" id="status">
                      <option value='ACTIVO' <?=$a?> >ACTIVO</option>
                      <option value='INACTIVO' <?=$b?> >INACTIVO</option>
                    </select>
                  </div>
                </div>
              </div>
              <div class="form-row">
                <div class="col-md-6">
                  <div class="position-relative form-group">
                    <label class="form-group-addon">Status</label>
                    <select class='selectpicker show-menu-arrow show-tick form-control' name="servicio" id="servicio">
                      <?php foreach ($servicio as $s) { ?>
                      <option value='0' selected style='display:none;'><?php echo $cliente;?></option>
                      <option value='<?php echo $s['cod_servicio'];?>'><?php echo $s['descripcion'];}?></option>
                    </select>
                  </div>
                </div>
              </div>
              <input type="button" class="btn btn-large btn-success" aria-describedby="update" id="update" value="Actualizar" />
              <input type="button" class="btn btn-large btn-info" aria-describedby="password" id="password" value="Reiniciar Contraseña" />
              <a href="?view=usuarios&mode=index" class="btn btn-medium btn-success">Volver</a>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

</div>
